//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticsAutomation
{
    using System;
    using System.Collections.Generic;
    
    public partial class CargoTransportation
    {
        public int ID { get; set; }
        public int CargoID { get; set; }
        public int TransportationID { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual Transportation Transportation { get; set; }
    }
}
