//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticsAutomation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cargo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cargo()
        {
            this.CargoTransportations = new HashSet<CargoTransportation>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int CargoTypeID { get; set; }
        public Nullable<int> Number { get; set; }
        public int SupplierID { get; set; }
        public string UnitMeasurement { get; set; }
        public Nullable<int> Weight { get; set; }
    
        public virtual CargoType CargoType { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CargoTransportation> CargoTransportations { get; set; }

        public override string ToString()
        {
            return String.Format($"[{ID}] {Name}");
        }
    }
}
