//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html
using SQLite;
using System;

namespace LogisticsAutomation
{
    public class SQLiteDb
    {
        string _path;
        public SQLiteDb(string path)
        {
            _path = path;
        }
        
        public void Create()
        {
            using (SQLiteConnection db = new SQLiteConnection(_path))
            {
                db.CreateTable<brand>();
                db.CreateTable<cargo>();
                db.CreateTable<cargo_transportation>();
                db.CreateTable<cargo_type>();
                db.CreateTable<client>();
                db.CreateTable<driver>();
                db.CreateTable<position>();
                db.CreateTable<supplier>();
                db.CreateTable<tariff>();
                db.CreateTable<transport>();
                db.CreateTable<transportation>();
                db.CreateTable<user>();
            }
        }
    }
    public partial class brand
    {
        [PrimaryKey, AutoIncrement]
        public Int64 id { get; set; }
        
        public String name { get; set; }
        
        public Int64? carrying { get; set; }
        
        public Int64? capacity { get; set; }
        
        public String description { get; set; }
        
    }
    
    public partial class cargo
    {
        [PrimaryKey, AutoIncrement]
        public Int64 id { get; set; }
        
        public Int64? cargo_type { get; set; }
        
        public Int64? number { get; set; }
        
        public Int64? supplier { get; set; }
        
        public String name { get; set; }
        
        public String unit_measurement { get; set; }
        
        public Int64? weight { get; set; }
        
    }
    
    public partial class cargo_transportation
    {
        [PrimaryKey, AutoIncrement]
        public Int64 id { get; set; }
        
        public Int64? cargo { get; set; }
        
        public Int64? transportation { get; set; }
        
    }
    
    public partial class cargo_type
    {
        [PrimaryKey, AutoIncrement]
        public Int64 id { get; set; }
        
        public String name { get; set; }
        
        public String description { get; set; }
        
        public Byte[] photo { get; set; }
        
    }
    
    public partial class client
    {
        [PrimaryKey, AutoIncrement]
        public Int64 id { get; set; }
        
        public String name { get; set; }
        
        public String address { get; set; }
        
        public String phone { get; set; }
        
        public String contact_person { get; set; }
        
        public String comments { get; set; }
        
    }
    
    public partial class driver
    {
        [PrimaryKey, AutoIncrement]
        public Int64 id { get; set; }
        
        public String name { get; set; }
        
        public String driver_category { get; set; }
        
        public String comments { get; set; }
        
    }
    
    public partial class position
    {
        [PrimaryKey, AutoIncrement]
        public Int64 id { get; set; }
        
        public String name { get; set; }
        
    }
    
    public partial class supplier
    {
        [PrimaryKey, AutoIncrement]
        public Int64 id { get; set; }
        
        public String name { get; set; }
        
        public String contact_person { get; set; }
        
        public String phone { get; set; }
        
        public String description { get; set; }
        
    }
    
    public partial class tariff
    {
        [PrimaryKey, AutoIncrement]
        public Int64 id { get; set; }
        
        public String name { get; set; }
        
        public Int64? per_kilometer { get; set; }
        
        public Int64? per_hour { get; set; }
        
        public Int64? per_kilogramm { get; set; }
        
        public String description { get; set; }
        
    }
    
    public partial class transport
    {
        [PrimaryKey, AutoIncrement]
        public Int64 id { get; set; }
        
        public Int64? brand { get; set; }
        
        public String entry_date { get; set; }
        
        public Int64? driver { get; set; }
        
        public String state_number { get; set; }
        
    }
    
    public partial class transportation
    {
        [PrimaryKey, AutoIncrement]
        public Int64 id { get; set; }
        
        public String order_date { get; set; }
        
        public Int64? transport { get; set; }
        
        public String place_delivery { get; set; }
        
        public Int64? client { get; set; }
        
        public Int64? tariff { get; set; }
        
        public Int64? kilometrage { get; set; }
        
        public Int64? time_spent { get; set; }
        
        public String additional_data { get; set; }
        
        public Int64? fuel_quantity_departure { get; set; }
        
        public Int64? fuel_quantity_coming { get; set; }
        
        public Int64? speedometer_value_departure { get; set; }
        
        public Int64? speedometer_value_coming { get; set; }
        
        public String date_arrival { get; set; }
        
    }
    
    public partial class user
    {
        [PrimaryKey, AutoIncrement]
        public Int64 id { get; set; }
        
        public String name { get; set; }
        
        public Int64? position { get; set; }
        
    }
    
}
