//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticsAutomation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transport()
        {
            this.Transportations = new HashSet<Transportation>();
        }
    
        public int ID { get; set; }
        public int BrandID { get; set; }
        public Nullable<System.DateTime> DateEntry { get; set; }
        public int DriverID { get; set; }
        public string StateNumber { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Driver Driver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transportation> Transportations { get; set; }

        public override string ToString()
        {
            return $"{StateNumber}";
        }
    }
}
