//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticsAutomation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transportation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transportation()
        {
            this.Cargoes = new HashSet<Cargo>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> DateOrder { get; set; }
        public int TransportID { get; set; }
        public string PlaceDelivery { get; set; }
        public int ClientID { get; set; }
        public int TariffID { get; set; }
        public Nullable<int> Kilometrage { get; set; }
        public Nullable<int> TravelTime { get; set; }
        public string AdditionalData { get; set; }
        public Nullable<int> FuelQuantityDeparture { get; set; }
        public Nullable<int> FuelQuantityComing { get; set; }
        public Nullable<int> SpeedometerValueDeparture { get; set; }
        public Nullable<int> SpeedometerValueComing { get; set; }
        public Nullable<System.DateTime> DateArrival { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Tariff Tariff { get; set; }
        public virtual Transport Transport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cargo> Cargoes { get; set; }
    }
}
